version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "eslint*"
          - "typescript-eslint*"
          - "@eslint/*"
          - "eslint-plugin-*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      tsup:
        patterns:
          - "tsup"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
