import { describe, it, expect } from "vitest";
import * as pkijs from "pkijs";
import * as fs from "fs";
import * as path from "path";
import { verifyTimestamp, ExtractedTimestamp } from "../../../core/src/pdf/extract.js";
import { TimestampInfo } from "../../../core/src/types.js";
import { vi } from "vitest";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

describe("Certificate Export", () => {
    it("should return certificates in validation result", async () => {
        // Read the dummy token generated by openssl
        const tokenPath = path.join(__dirname, "../fixtures/dummy_token.der");
        const token = fs.readFileSync(tokenPath); // Returns Buffer, which is Uint8Array subclass

        // Mock verification to pass (since our dummy token might be just SignedData not valid timestamp)
        // Actually, verifyTimestamp *does* verify signature.
        // Our openssl generated token IS validly signed by the generated cert.
        // So verify() should pass if we don't check chain.
        // But let's keep the mock to be safe and fast.
        const verifySpy = vi.spyOn(pkijs.SignedData.prototype, "verify").mockResolvedValue({
            signatureVerified: true,
            signerVerified: true,
            message: "OK",
            code: 0,
            date: new Date(),
            certificatePath: [],
        } as unknown as pkijs.SignedDataVerifyResult);

        const timestamp: ExtractedTimestamp = {
            token: new Uint8Array(token),
            info: {} as TimestampInfo,
            fieldName: "Test",
            coversWholeDocument: true,
            verified: true,
            byteRange: [0, 0, 0, 0],
        };

        const result = await verifyTimestamp(timestamp);

        expect(result.certificates).toBeDefined();
        // openssl cms -sign includes the signer certificate by default
        const certs = result.certificates ?? [];
        expect(certs.length).toBeGreaterThanOrEqual(1);
        expect(certs[0]).toBeInstanceOf(pkijs.Certificate);

        // We can check format is correct
        if (certs[0]) {
            console.warn("Extracted cert serial:", certs[0].serialNumber.valueBlock.valueDec);
        }

        verifySpy.mockRestore();
    });
});
